export const OPTION_NAME = 'v'
export const TIME_RANGE_START = 'timeRangeStart'
export const TIME_RANGE_STOP = 'timeRangeStop'
export const WINDOW_PERIOD = 'windowPeriod'

enum FluxBoundaries {
  START = '^',
  QUOTE = '"',
  SPACE = '\\s',
  NEWLINE = '\\n',
  COMMENT = '\\/\\/',
  // and, or, not require space around them
  ADD = '\\+',
  SUB = '\\-',
  MUL = '\\*',
  DIV = '\\/',
  MOD = '\\%',
  EQ = '\\=\\=',
  LT = '\\<',
  GT = '\\>',
  LTE = '\\<=',
  GTE = '\\>\\=',
  NEQ = '\\!\\=',
  REGEXEQ = '\\=\\~',
  REGEXNEQ = '\\!\\~',
  ASSIGN = '\\=',
  ARROW = '\\=\\>',
  LPAREN = '\\(',
  RPAREN = '\\)',
  LBRACK = '\\[',
  RBRACK = '\\]',
  LBRACE = '\\{',
  RBRACE = '\\}',
  COLON = '\\:',
  COMMA = '\\,',
  EOF = '$',
}

const FLUX_BOUNDARY = [
  FluxBoundaries.START,
  FluxBoundaries.QUOTE,
  FluxBoundaries.SPACE,
  FluxBoundaries.NEWLINE,
  FluxBoundaries.COMMENT,
  FluxBoundaries.ADD,
  FluxBoundaries.SUB,
  FluxBoundaries.MUL,
  FluxBoundaries.DIV,
  FluxBoundaries.MOD,
  FluxBoundaries.EQ,
  FluxBoundaries.LT,
  FluxBoundaries.GT,
  FluxBoundaries.LTE,
  FluxBoundaries.GTE,
  FluxBoundaries.NEQ,
  FluxBoundaries.REGEXEQ,
  FluxBoundaries.REGEXNEQ,
  FluxBoundaries.ASSIGN,
  FluxBoundaries.ARROW,
  FluxBoundaries.LPAREN,
  FluxBoundaries.RPAREN,
  FluxBoundaries.LBRACK,
  FluxBoundaries.RBRACK,
  FluxBoundaries.LBRACE,
  FluxBoundaries.RBRACE,
  FluxBoundaries.COLON,
  FluxBoundaries.COMMA,
  FluxBoundaries.EOF,
].join('|')

export const BOUNDARY_GROUP = `(${FLUX_BOUNDARY})`
