FROM circleci/node:lts-stretch-browsers

USER root

COPY package.json /selenium-accept-infl2/package.json

WORKDIR /selenium-accept-infl2

RUN npm install

COPY . /selenium-accept-infl2

RUN \
  mkdir report

ENV PATH $PATH:./node_modules/.bin

CMD cucumber-js
