FROM ubuntu:xenial

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    asciidoc \
    autoconf \
    build-essential \
    curl \
    docbook-xsl \
    git \
    libtool \
    make \
    mercurial \
    pkg-config \
    python \
    python-boto \
    python-software-properties \
    rpm \
    ruby \
    ruby-dev \
    software-properties-common \
    wget \
    xmlto \
    zip

RUN gem install fpm

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y

# setup environment
ENV GO_VERSION  1.13
ENV GOARCH      amd64
ENV GOROOT      /usr/local/go
ENV GOPATH      /root/go
ENV PATH        $GOPATH/bin:$GOROOT/bin:/root/.cargo/bin:$PATH
ENV PROJECT_DIR /root/influxdb
ENV PKG_CONFIG  /root/influxdb/pkg-config.sh

# install go
RUN wget --no-verbose https://storage.googleapis.com/golang/go${GO_VERSION}.linux-${GOARCH}.tar.gz -O- | tar -C /usr/local/ -zxf-

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR
VOLUME  $PROJECT_DIR

ENTRYPOINT [ "/root/influxdb/build.py" ]
