FROM rust:slim-buster

RUN groupadd -g 1500 rust \
  && useradd -u 1500 -g rust -s /bin/bash -m rust

USER rust

RUN mkdir ~/.influxdb_iox
RUN ls -la ~/.influxdb_iox

COPY target/release/influxdb_iox /usr/bin/influxdb_iox

EXPOSE 8080 8082

CMD ["influxdb_iox"]
