export const SET_STATUS_PAGE_AUTOREFRESH = 'SET_STATUS_PAGE_AUTOREFRESH'
export const SET_STATUS_PAGE_TIME_RANGE = 'SET_STATUS_PAGE_TIME_RANGE'

export const GET_JSON_FEED_REQUESTED = 'GET_JSON_FEED_REQUESTED'
export const GET_JSON_FEED_COMPLETED = 'GET_JSON_FEED_COMPLETED'
export const GET_JSON_FEED_FAILED = 'GET_JSON_FEED_FAILED'
