[package]
name = "influxdb3_startup"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.influxdb3]
build = "Core"

[dependencies]
chrono.workspace = true
observability_deps = { path = "../core/observability_deps" }
tokio.workspace = true

[dev-dependencies]
test_helpers = { path = "../core/test_helpers" }

[lints]
workspace = true
