// Code generated by "stringer -type=CacheStatus"; DO NOT EDIT.

package tsm1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CacheStatusOkay-0]
	_ = x[CacheStatusSizeExceeded-1]
	_ = x[CacheStatusAgeExceeded-2]
	_ = x[CacheStatusColdNoWrites-3]
}

const _CacheStatus_name = "CacheStatusOkayCacheStatusSizeExceededCacheStatusAgeExceededCacheStatusColdNoWrites"

var _CacheStatus_index = [...]uint8{0, 15, 38, 60, 83}

func (i CacheStatus) String() string {
	if i < 0 || i >= CacheStatus(len(_CacheStatus_index)-1) {
		return "CacheStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CacheStatus_name[_CacheStatus_index[i]:_CacheStatus_index[i+1]]
}
