export const TEMPLATE_VARIABLE_SELECTED = 'TEMPLATE_VARIABLE_SELECTED'

export const TEMPLATE_VARIABLES_SELECTED_BY_NAME =
  'TEMPLATE_VARIABLES_SELECTED_BY_NAME'

export const LINKS_GET_REQUESTED = 'LINKS_GET_REQUESTED'
export const LINKS_GET_COMPLETED = 'LINKS_GET_COMPLETED'
export const LINKS_GET_FAILED = 'LINKS_GET_FAILED'
