package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSourcesIDKapacitorsKapaIDHandlerFunc turns a function with the right signature into a get sources ID kapacitors kapa ID handler
type GetSourcesIDKapacitorsKapaIDHandlerFunc func(context.Context, GetSourcesIDKapacitorsKapaIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSourcesIDKapacitorsKapaIDHandlerFunc) Handle(ctx context.Context, params GetSourcesIDKapacitorsKapaIDParams) middleware.Responder {
	return fn(ctx, params)
}

// GetSourcesIDKapacitorsKapaIDHandler interface for that can handle valid get sources ID kapacitors kapa ID params
type GetSourcesIDKapacitorsKapaIDHandler interface {
	Handle(context.Context, GetSourcesIDKapacitorsKapaIDParams) middleware.Responder
}

// NewGetSourcesIDKapacitorsKapaID creates a new http.Handler for the get sources ID kapacitors kapa ID operation
func NewGetSourcesIDKapacitorsKapaID(ctx *middleware.Context, handler GetSourcesIDKapacitorsKapaIDHandler) *GetSourcesIDKapacitorsKapaID {
	return &GetSourcesIDKapacitorsKapaID{Context: ctx, Handler: handler}
}

/*GetSourcesIDKapacitorsKapaID swagger:route GET /sources/{id}/kapacitors/{kapa_id} getSourcesIdKapacitorsKapaId

Configured kapacitors

These kapacitors are used for monitoring and alerting.

*/
type GetSourcesIDKapacitorsKapaID struct {
	Context *middleware.Context
	Handler GetSourcesIDKapacitorsKapaIDHandler
}

func (o *GetSourcesIDKapacitorsKapaID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetSourcesIDKapacitorsKapaIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
