package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	context "golang.org/x/net/context"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostDashboardsHandlerFunc turns a function with the right signature into a post dashboards handler
type PostDashboardsHandlerFunc func(context.Context, PostDashboardsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDashboardsHandlerFunc) Handle(ctx context.Context, params PostDashboardsParams) middleware.Responder {
	return fn(ctx, params)
}

// PostDashboardsHandler interface for that can handle valid post dashboards params
type PostDashboardsHandler interface {
	Handle(context.Context, PostDashboardsParams) middleware.Responder
}

// NewPostDashboards creates a new http.Handler for the post dashboards operation
func NewPostDashboards(ctx *middleware.Context, handler PostDashboardsHandler) *PostDashboards {
	return &PostDashboards{Context: ctx, Handler: handler}
}

/*PostDashboards swagger:route POST /dashboards postDashboards

Create new Dashboard

*/
type PostDashboards struct {
	Context *middleware.Context
	Handler PostDashboardsHandler
}

func (o *PostDashboards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostDashboardsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(context.Background(), Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
