###
# Dockerfile used for deploying IOx
##
FROM debian:buster-slim

RUN apt-get update \
    && apt-get install -y libssl1.1 libgcc1 libc6 \
	&& rm -rf /var/lib/{apt,dpkg,cache,log}

RUN groupadd -g 1500 rust \
  && useradd -u 1500 -g rust -s /bin/bash -m rust

USER rust

RUN mkdir ~/.influxdb_iox
RUN ls -la ~/.influxdb_iox

COPY target/release/influxdb_iox /usr/bin/influxdb_iox

EXPOSE 8080 8082

ENTRYPOINT ["influxdb_iox"]

CMD ["server"]
