#!/bin/bash -e
#
# InfluxDB IOx FlightSQL JDBC Test program. See README.md in this
# directory for example use
#
# Compiles and runs Main.java, downloading the FligthSQL JDBC driver if necessary

# https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

JDBC_DRIVER="flight-sql-jdbc-driver-10.0.0.jar"

# download driver if not present
make -C $SCRIPT_DIR $JDBC_DRIVER

# Help track down https://github.com/influxdata/influxdb_iox/issues/6967
ls -ltr

# Compile
make -C $SCRIPT_DIR Main.class

# Run the code and pass along command line arguments
java --add-opens=java.base/java.nio=ALL-UNNAMED -classpath "$SCRIPT_DIR:$SCRIPT_DIR/$JDBC_DRIVER" Main "$@"
