from(db:"testdb")
  |> range(start: 2018-05-21T13:09:22.885021542Z)
  |> filter(fn: (r) => r._measurement ==  "swap")
  |> map(mergeKey:false, fn: (r) => {_measurement:r._measurement, time: r._time, used_percent:r._value})
  |> yield(name:"0")