#!/bin/bash
set -o nounset  \
    -o errexit  \
    -o pipefail

REGEX_TAG='v([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)'

# If no tag could be found for the corresponding commit, assume that this
# is being built from an unversioned branch. In which case, this will
# construct a version that is compatible with Debian versioning:
# ${PREFIX}-<< short commit hash >>
if [[ ${CIRCLE_TAG:-} =~ ^${REGEX_TAG} ]]
then
  cat <<EOF >>"${BASH_ENV}"
export VERSION="${CIRCLE_TAG:1}"
export MAJOR="${BASH_REMATCH[1]}"
export MINOR="${BASH_REMATCH[2]}"
export PATCH="${BASH_REMATCH[3]}"
export RELEASE="1"
EOF
else
  cat <<EOF >>"${BASH_ENV}"
export VERSION="${PREFIX}-${CIRCLE_SHA1:0:8}"
export MAJOR=""
export MINOR=""
export PATCH=""
export RELEASE=""
EOF
fi
