#!/bin/bash
set -o errexit \
    -o nounset \
    -o pipefail

cp -r /tmp/workspace/packages packages

# CircleCI mangles environment variables with newlines. This key contians
# escaped newlines. For `gpg` to import the key, it requires `echo -e` to
# expand the escape sequences.
gpg --batch --import <<<"$(echo -e "${GPG_1X_PRIVATE_KEY}")"

# TODO(bnpfeife): replace with code signing server
for target in packages/*
do
  gpg                            \
    --batch                      \
    --pinentry-mode=loopback     \
    --passphrase "${PASSPHRASE}" \
    --detach-sign                \
    --armor "${target}"
done
